# eureka.client.serviceUrl.defaultZone=http://eureka-primary:8011/eureka/

# eureka.client.serviceUrl.defaultZone=http://eureka-secondary:8012/eureka/

# eureka.client.serviceUrl.defaultZone=http://eureka-tertiary:8013/eureka/
